language: python
python:
- 3.6
install:
- pip install --upgrade pip numpy
- pip install .
- pip install -r requirements-dev.txt
script:
- coverage run -m pytest
- coverage report -m
- codecov
- flake8
- make -C docs html
- touch docs/build/html/.nojekyll
deploy:
- provider: pages:git
  verbose: true
  token: "$GITHUB_TOKEN"
  edge: true
  local_dir: "./docs/build/html/"
  keep_history: true
  target-branch: gh-pages
  on:
    branch: master
after_success:
- openssl aes-256-cbc -K $encrypted_3a68a39d21bf_key -iv $encrypted_3a68a39d21bf_iv
  -in docs/key.enc -out docs/key -d
